export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST"
export const GET_POSTS_RESOLVE = "GET_POSTS_RESOLVE"
export const GET_POSTS_REJECT = "GET_POSTS_REJECT"

export const GET_POSTID_REQUEST = "GET_POSTID_REQUEST"
export const GET_POSTID_RESOLVE = "GET_POSTID_RESOLVE"
export const GET_POSTID_REJECT = "GET_POSTID_REJECT"